# Generated by Django 4.1.2 on 2022-11-08 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa_rpg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_inventory', models.CharField(default='', max_length=1000)),
                ('dungeon_inventory', models.CharField(default='', max_length=1000)),
                ('max_inventory', models.IntegerField(default=2)),
                ('question_template', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ReportAndCommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='question',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='log',
            name='log_questions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='log',
            name='log_report_question',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='activity',
            field=models.CharField(default='index', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='awake',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='dungeon_currency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='luck',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='player',
            name='question_max_currency',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='player',
            name='question_rate_currency',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='max_currency',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='question',
            name='rate',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_text',
            field=models.CharField(default=';;;;;;;;;;', max_length=1000),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='max_hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='currency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='damage',
            field=models.IntegerField(default=20),
        ),
        migrations.DeleteModel(
            name='Commend',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='reportandcommend',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_rpg.question'),
        ),
        migrations.AddField(
            model_name='reportandcommend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_rpg.player'),
        ),
    ]
