# Generated by Django 4.1.5 on 2024-05-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_rpg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='policy',
            field=models.BooleanField(default=True),
        ),
    ]
