# Generated by Django 4.1.2 on 2022-11-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_rpg', '0002_inventory_reportandcommend_remove_report_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='max_inventory',
            field=models.IntegerField(default=3),
        ),
    ]
