# Generated by Django 4.1.5 on 2024-05-08 16:10

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qa_rpg', '0002_user_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=254)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
    ]
