# Generated by Django 4.1 on 2022-10-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_rpg', '0002_alter_log_log_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
