# Generated by Django 4.1.2 on 2022-10-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_rpg', '0003_question_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='activity',
            field=models.CharField(default='index', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='dungeon_currency',
            field=models.IntegerField(default=0),
        ),
    ]
