# Generated by Django 4.1 on 2022-10-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_rpg", "0006_alter_log_log_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.CharField(default="test category", max_length=100),
            preserve_default=False,
        ),
    ]
