# Generated by Django 4.1 on 2022-10-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_rpg", "0007_question_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player", name="luck", field=models.FloatField(default=0.25),
        ),
    ]
