# Generated by Django 4.1 on 2022-10-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_rpg", "0008_alter_player_luck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="current_hp",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="player", name="max_hp", field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="question",
            name="currency",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="question", name="damage", field=models.IntegerField(default=20),
        ),
    ]
