# Generated by Django 4.1.2 on 2022-11-03 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa_rpg', '0011_alter_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_inventory', models.CharField(default='', max_length=1000)),
                ('dungeon_inventory', models.CharField(default='', max_length=1000)),
                ('max_inventory', models.IntegerField(default=3)),
                ('question_template', models.CharField(default='', max_length=1000)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_rpg.player')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAndCommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_rpg.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='question',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='log',
            name='log_questions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Commend',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
