# Generated by Django 4.1.2 on 2022-11-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_rpg', '0013_log_log_report_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='max_inventory',
            field=models.IntegerField(default=2),
        ),
    ]
