# Generated by Django 4.1 on 2022-11-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_rpg", "0014_alter_inventory_max_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="status",
            field=models.CharField(default="", max_length=50),
        ),
    ]
