# Generated by Django 4.1.2 on 2022-11-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_rpg', '0015_player_awake'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rate',
            field=models.IntegerField(default=5),
        ),
    ]
